# Generated by Django 5.0.1 on 2024-02-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_alter_signup_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Cpassword',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
