# Generated by Django 5.0.1 on 2024-02-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_alter_signup_cpassword_alter_signup_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='Cpassword',
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
