# Generated by Django 5.0.1 on 2024-02-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0008_alter_signup_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=300, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
    ]
