# Generated by Django 5.0.1 on 2024-02-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0010_remove_login_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='fullname',
            field=models.CharField(max_length=300),
        ),
    ]
