# Generated by Django 5.0.1 on 2024-02-08 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0011_alter_signup_fullname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
