# Generated by Django 5.0.1 on 2024-02-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0016_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
