# Generated by Django 5.0.1 on 2024-02-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0020_signup_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
