# Generated by Django 5.0.1 on 2024-02-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0022_alter_signup_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signup',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
