# Generated by Django 5.0.1 on 2024-02-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0023_signup_is_admin_signup_last_login_alter_signup_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='email',
        ),
        migrations.AlterField(
            model_name='signup',
            name='fullname',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
