# Generated by Django 5.0.1 on 2024-02-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0024_remove_signup_email_alter_signup_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
