# Generated by Django 5.0.1 on 2024-02-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0026_alter_signup_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='signup',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='signup',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
