# Generated by Django 5.0.1 on 2024-02-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0031_signup_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
