# Generated by Django 5.0.1 on 2024-02-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0032_alter_signup_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='signup',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
