# Generated by Django 5.0.1 on 2024-02-21 06:26

import CRM.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0034_signup_is_staff_signup_is_superuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='signup',
            managers=[
                ('objects', CRM.models.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='signup',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='signup',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='signup',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='signup',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
