# Generated by Django 5.0.1 on 2024-02-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0035_alter_signup_managers_remove_signup_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='signup',
            managers=[
            ],
        ),
    ]
