# Generated by Django 5.0.1 on 2024-05-27 05:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='qid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
