# Generated by Django 5.0.1 on 2024-05-09 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='option',
        ),
    ]
