# Generated by Django 5.0.1 on 2024-05-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0002_remove_poll_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='options',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
