# Generated by Django 5.0.1 on 2024-05-11 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0003_poll_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='options',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='user',
        ),
        migrations.CreateModel(
            name='PollCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_id', models.IntegerField(editable=False, unique=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('option', models.CharField(blank=True, max_length=255, null=True)),
                ('vote', models.IntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Poll.pollcode')),
            ],
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Poll.pollcode'),
        ),
    ]
