# Generated by Django 5.0.1 on 2024-05-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0004_remove_poll_options_remove_poll_user_pollcode_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollcode',
            name='poll_id',
            field=models.CharField(default=None, editable=False, unique=True),
        ),
    ]
