# Generated by Django 5.0.1 on 2024-05-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0005_alter_pollcode_poll_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollcode',
            name='poll_id',
            field=models.CharField(editable=False),
        ),
    ]
