# Generated by Django 5.0.1 on 2024-05-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0007_poll_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='poll',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_id',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
