# Generated by Django 5.0.1 on 2024-05-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0008_alter_option_poll_alter_poll_poll_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='option',
        ),
        migrations.RemoveField(
            model_name='option',
            name='vote',
        ),
        migrations.AddField(
            model_name='option',
            name='options',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='option',
            name='votes',
            field=models.JSONField(default=list),
        ),
    ]
