# Generated by Django 5.0.1 on 2024-05-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0009_remove_option_option_remove_option_vote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='options',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='option',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
