# Generated by Django 5.0.1 on 2024-05-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0010_alter_option_options_alter_option_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollcode',
            name='num_of_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pollcode',
            name='session',
            field=models.BooleanField(default=False),
        ),
    ]
