# Generated by Django 5.0.1 on 2024-05-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0011_pollcode_num_of_people_pollcode_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollcode',
            name='session',
        ),
        migrations.AddField(
            model_name='pollcode',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
