# Generated by Django 5.0.1 on 2024-04-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomInfo', '0002_room_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_comment', models.IntegerField()),
                ('commnets', models.CharField(max_length=255)),
            ],
        ),
    ]
