# Generated by Django 5.0.1 on 2024-04-02 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomInfo', '0003_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commnets',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RoomInfo.room'),
        ),
    ]
