# Generated by Django 5.0.1 on 2024-04-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomInfo', '0005_comments_no_upvoted_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='comments',
            name='no_of_comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='num_of_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='num_of_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(editable=False),
        ),
    ]
