# Generated by Django 5.0.1 on 2024-04-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomInfo', '0007_room_limit_people_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='limit_people_num',
            field=models.IntegerField(default=9999),
        ),
    ]
