# Generated by Django 5.0.1 on 2024-04-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomInfo', '0008_participants_alter_room_limit_people_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participants',
        ),
        migrations.AddField(
            model_name='comments',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
