# Generated by Django 5.0.1 on 2024-04-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoomInfo', '0009_delete_participants_comments_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='no_of_comment',
        ),
    ]
