# Generated by Django 5.0.1 on 2024-04-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomInfo', '0012_rename_room_id_comments_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='no_upvoted_comments',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='upvoted_comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='comments',
            name='room',
            field=models.CharField(),
        ),
    ]
