# Generated by Django 5.0.1 on 2024-04-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomInfo', '0013_remove_comments_no_upvoted_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='room',
            field=models.CharField(default=None),
        ),
    ]
