# Generated by Django 5.0.1 on 2024-04-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomInfo', '0014_alter_comments_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='read',
        ),
        migrations.AddField(
            model_name='comments',
            name='message',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
