# Generated by Django 5.0.1 on 2024-04-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoomInfo', '0015_remove_comments_comments_remove_comments_read_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
