# Generated by Django 5.0.1 on 2024-04-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomInfo', '0016_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(default=None)),
                ('user', models.CharField(default=None, max_length=255)),
                ('message', models.CharField(default=None, max_length=500)),
            ],
        ),
    ]
