# Generated by Django 5.0.1 on 2024-04-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomInfo', '0017_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='upvoted_message',
            field=models.BooleanField(default=False),
        ),
    ]
