# Generated by Django 5.0.1 on 2024-04-26 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomInfo', '0018_comments_upvoted_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='upvoted_message',
        ),
        migrations.AlterField(
            model_name='comments',
            name='room',
            field=models.IntegerField(default=None),
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RoomInfo.comments')),
            ],
        ),
    ]
