# Generated by Django 5.0.1 on 2024-04-26 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoomInfo', '0019_remove_comments_upvoted_message_alter_comments_room_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
