# Generated by Django 5.0.1 on 2024-04-26 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoomInfo', '0022_room_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
    ]
