# Generated by Django 5.0.1 on 2024-05-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomInfo', '0025_comment_vote_delete_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='session',
            field=models.BooleanField(default=False),
        ),
    ]
