# Generated by Django 5.0.1 on 2024-05-14 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoomInfo', '0026_room_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='session',
            new_name='active',
        ),
    ]
