# Generated by Django 5.0.1 on 2024-05-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomInfo', '0028_alter_room_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.CharField(default=None, max_length=255)),
                ('question', models.CharField(max_length=255)),
                ('options', models.CharField(default=None, max_length=255)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
