# Generated by Django 5.0.1 on 2024-05-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomInfo', '0030_alter_comment_id_alter_comment_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='room',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
